### PR TITLE
set version to 0.2.3

### PR DESCRIPTION
**Pull request by eddelbuettel**
not to be to too stubborn but I think we should reserve 0.3.0 for a "bigger" change

obviously Whit's call so feel free to close if 0.3.0 was the desired number

### CODE REVIEW

**Comment by johnlaing** [comment]
The change in functionality is small, but it breaks backwards compatibility of (nearly?) every function in the package. To me that warrants a semi-major version bump. It's not like I'm calling for 1.0.

**Comment by eddelbuettel** [comment]
Very true, but we broke interfaces before in the 0.2.1.* series.  [ Speaking of which my PR is wrong as 0.2.2.0 should follow 0.2.1.*; will amend. ]  

No strong feelings either way but I usually bump on feature changes.  Which 'making con default is' but in a way I feel we're still polishing things off.   

Whit's call, no hurt feelings if 0.3.0 stands.   Just "too version-inflationary" for my tastes, but heck, not my package.

**Comment by eddelbuettel** [comment]
So I take it that is a no?

**Comment by armstrtw** [comment]
I don't really care. you guys can work it out.

**Comment by eddelbuettel** [comment]
John's changes did not work for me, or did not work in the way I wanted them.   Now a connection is created and stored on load so we get

```{.r}
R> library(Rblpapi)
R> bdp(c("VXX US Equity", "SPY US Equity"), c("OPEN", "HIGH", "LOW", "PX_CLOSE"))
                HIGH    LOW   OPEN PX_CLOSE
VXX US Equity  21.57  20.77  21.54    20.81
SPY US Equity 210.77 209.28 209.40   210.72
R> 
```

which I like better.  Thoughts, @johnlaing and @armstrtw ?

**Comment by armstrtw** [comment]
I think he had a specific reason for now wanting to initiate on load...

I'm indifferent to the approaches, but equivalently, just drop blpConnect() into your .Rprofile.  Does that not do the trick?

**Comment by eddelbuettel** [comment]
It would be nice if you he could join the discussion and/or could have discussed the changed before making them.

Anyway, the PR now connect in `.onAttach()` if and only if you have the values in `options()` -- so the integration testing at Travis does not connect, but it does on our machines at work.  This is what I like best as a design, and will continue to use.  You are free to take it up, or ignore it.

Adding `blpConnect()` in `Rprofile,site` is a much heavier hammer I do want to use.

We can discuss further, or you can just watch my repo and take patches as you like.  I upload tarballs from my tree to [ghrr](http://ghrr.github.io/drat) anyway and now deplay 0.2.1.1 from there ...

**Comment by armstrtw** [comment]
The connection discussion had been here:
https://github.com/armstrtw/Rblpapi/issues/28

I'm sure JL will reappear. It's Friday, and this has been a very very long and volatile month for some of us in the fixed income space...

**Pull request merged**
