### PR TITLE
bdp updates

### PR DESCRIPTION
**Pull request by eddelbuettel**
small simplifications to the C++ side of bdp
new help page
small grammar fixes to existing manual pages

plan to update bdh and bds next

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Pinging @armstrtw -- if you have a moment, this should be straightforward and I can then move on to bdh and bds.

**Comment by armstrtw** [comment]
I'm on a train with just my phone,  but will get to it this aft.

**Comment by eddelbuettel** [comment]
Anytime this week would be great.  Was just (rudely) pinging as I had not heard otherwise...

**Comment by eddelbuettel** [comment]
Hold on a few minutes, I left a brown-bag bug in there.  Will amend.

**Comment by eddelbuettel** [comment]
Better now. I had both broken bdp and bdh.  Bdh still need some spit (and a manual page etc).

**Pull request merged**
